hazel:
  isDev: true

project:
  local:
    enabled: true
    enableNodePorts: true

# minio:
#   tenant:
#     pools:
#       - servers: 1
#         name: pool-0
#         volumesPerServer: 1
#         size: 5Gi
#   ingress:
#     api:
#       enabled: true
#       ingressClassName: "traefik"
#       host: files.hazel.localhost
#       path: /
#       pathType: Prefix
#       annotations:
#         cert-manager.io/cluster-issuer: mkcert-issuer
#       tls:
#         - hosts:
#             - files.hazel.localhost
#           secretName: hazel-files-local-hazel-cert
#     console:
#       enabled: true
#       ingressClassName: "traefik"
#       host: minio-console.hazel.localhost
#       path: /
#       pathType: Prefix
#       annotations:
#         cert-manager.io/cluster-issuer: mkcert-issuer
#       tls:
#         - hosts:
#             - minio-console.hazel.localhost
#           secretName: hazel-minio-studio-local-hazel-cert
