# Override values for development
# Coordinate changes here with changes to ./infra.yaml that get applied to the hazel-infra chart for k3d/dev

hazel:
  isDev: true
  local:
    # if set and `isDev: true`, will mount a volume from this path (useful for local development)
    # WARNING: this path will be inside the k3d container if using k3d, not your host machine,
    # so if you want to use your host machine path, you need to mount it in k3d first at cluster creation time!
    src: true
    enableNodePorts: true

  backups:
    media:
      enabled: true
