global:
  namespace: hazel
  hazelVersion: "1.0.1"
  instanceId: "hazel-instance"
  redirectHttp: true

project:
  local:
    enabled: false
    enableNodePorts: false
# .Values.hazel.certManager.issuers
hazel:
  isDev: false
  dev:
    files:
      lbIP: ""
    backups:
      lbIP: ""

  certManager:
    issuers: []
      # - server: https://acme-staging-v02.api.letsencrypt.org/directory
      #   name: "letsencrypt-staging"
      #   kind: "Issuer"
      #   email: "certs@hazel.localhost"
      #   privateKeySecretRef: "le-key-staging"
      # - server: https://acme-v02.api.letsencrypt.org/directory
      #   name: "letsencrypt-prod"
      #   kind: "Issuer"
      #   email: "certs@hazel.localhost"
      #   privateKeySecretRef: "le-key-prod"

# Common labels and annotations
commonLabels:
  app.kubernetes.io/part-of: hazel
  # app.kubernetes.io/managed-by: Helm
  # Additional common labels can be added here

commonAnnotations: {}
  # App version annotation will be automatically added
  # Additional annotations can be added here

db:
  enabled: true
  backups:
    enabled: true
    schedule: "0 30 2 * * *"  # At 02:30:00 (UTC) every day
    retention: 7d          # keep 7 backups
    barmanObjectName: s3-store-db
    destinationPath: "hazel-db-backups"
    host: backups.hazel.localhost
    port: 80
    useSSL: false
    walCompression: bzip2  # bzip2;gzip;lz4;snappy;xz;zstd
    dataCompression: bzip2  # bzip2;gzip;snappy
    s3Credentials:
      accessKeyId:
        name: s3-backups
        key: username
      secretAccessKey:
        name: s3-backups
        key: password

  cluster:
    enabled: true
    name: db-cluster
    instances: 1
    image:
      repository: "ghcr.io/cloudnative-pg/postgresql"
      tag: "18-minimal-trixie"
      pullPolicy: IfNotPresent
    superuser:
      credentials: db-super-credentials
    user:
      credentials: hazel-db-credentials
    storage:
      size: 5Gi

    managed:
      services:
        disabledDefaultServices: ["ro", "r"]

    # To bootstrap a new database (needs db-migratejob.yaml afterwards)
    bootstrap:
      enabled: true
      dbName: hazel
      dbOwner: hazel
      recovery:
        # To restore from a backup
        # backupSource: true
        barmanObjectName: s3-store-db

    walArchive:
      enabled: true
      barmanObjectName: s3-store-db

    extraRoles: []
      # example:
      # - name: notes
      #   ensure: present
      #   comment: "hazel Application User"
      #   login: true
      #   createdb: true
      #   createrole: false
      #   replication: false
      #   bypassrls: false
      #   passwordSecret:
      #     name: notes-db-credentials

minio:
  enabled: false
  extendedOperator:
    # Set this to create a user for hazel to use for storage
    # The secret with this name must exist and contain keys `secretKey`
    # You can use the provided `kube/kube/k3d-deploy/secrets/hazel-infra/s3-storage.json` to create such a secret
    user:
      name: s3-storage
      secretName: s3-storage
      secretKeyName: password

    buckets:
      - name: hazel
        versioning: true
      - name: hazeluploads
        versioning: true
      - name: hazelgrades
        versioning: true
      - name: hazelprofiles
        versioning: true
      - name: public
        versioning: true
        public: true
    extraBuckets: []
      # example:
      # - name: extra-bucket
      #   versioning: false

  # see https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant.yaml
  tenant:
    name: minio-storage
    exposeServices:
      minio: false
      console: false

    # DO NOT SET BUCKETS HERE! They are NOT managed by this operator - see extendedOperator above!
    # buckets: []

    configSecret:
      name: minio-env
      existingSecret: true

    certificate:
      requestAutoCert: false

    # pools:
    #   - servers: 1
    #     name: pool-0
    #     volumesPerServer: 1
    #     size: 5Gi

  ingress:
    api:
      enabled: false
      ingressClassName: "traefik"
      labels: { }
      annotations: { }
      tls: [ ]
      host: files.hazel.localhost
      path: /
      pathType: Prefix
    console:
      enabled: false
      ingressClassName: "traefik"
      labels: { }
      annotations: { }
      tls: [ ]
      host: minio-console.hazel.localhost
      path: /
      pathType: Prefix

redis:
  externalConfig:
    enabled: true
  enabled: true
  redisStandalone:
    name: redis  # apparently MUST be set or it will default to the release name
    tag: "v7.4.8"
    # tag: "v8.4.2"
