# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  namespace: hazel
  hazelVersion: "1.0.1"
  instanceId: "hazel-instance"
  redirectHttp: true
  imageRegistry: ""
  ## e.g:
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""
  ## Compatibility adaptations for Kubernetes platforms
  ##
  compatibility:
    ## Compatibility adaptations for Openshift
    ##
    openshift:
      ## @param global.compatibility.openshift.adaptSecurityContext Adapt the securityContext sections of the deployment to make them compatible with Openshift restricted-v2 SCC: remove runAsUser, runAsGroup and fsGroup and let the platform use their allowed default IDs. Possible values: auto (apply if the detected running cluster is Openshift), force (perform the adaptation always), disabled (do not perform adaptation)
      ##
      adaptSecurityContext: auto

## @section Common parameters
##

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param apiVersions Override Kubernetes API versions reported by .Capabilities
##
apiVersions: []
## @param nameOverride String to partially override common.names.name
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels:
  app.kubernetes.io/part-of: hazel
  # app.kubernetes.io/managed-by: Helm

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []
## @param usePasswordFiles Mount credentials as files instead of using an environment variable
##
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity


project:
  local:
    enabled: false
    enableNodePorts: false
hazel:
  isDev: false
  dev:
    files:
      lbIP: ""
    backups:
      lbIP: ""
  backups:
    image:
      repository: minio/mc
      tag: RELEASE.2025-08-13T08-35-41Z
      pullPolicy: IfNotPresent

    media:
      enabled: false
      strategy:
        type: Recreate
      destination:
        bucketName: "hazel-media-backups"
        host: backups.hazel.localhostz
        port: 80
        useSSL: false
        accessKey:
          secretName: s3-backups
          secretKey: username
        secretKey:
          secretName: s3-backups
          secretKey: password


  certManager:
    issuers: []
      # - server: https://acme-staging-v02.api.letsencrypt.org/directory
      #   name: "letsencrypt-staging"
      #   kind: "Issuer"
      #   email: "certs@hazel.localhost"
      #   privateKeySecretRef: "le-key-staging"
      # - server: https://acme-v02.api.letsencrypt.org/directory
      #   name: "letsencrypt-prod"
      #   kind: "Issuer"
      #   email: "certs@hazel.localhost"
      #   privateKeySecretRef: "le-key-prod"

dbClusters:
  db:
    enabled: true
    backups:
      enabled: false
      schedule: "0 30 2 * * *"  # At 02:30:00 (UTC) every day
      retention: 3d          # keep 3 backups
      barmanObjectName: s3-store-db
      destinationPath: "db-backups"
      host: backups.hazel.localhost
      port: 80
      useSSL: false
      walCompression: bzip2  # bzip2;gzip;lz4;snappy;xz;zstd
      dataCompression: bzip2  # bzip2;gzip;snappy
      s3Credentials:
        accessKeyId:
          name: s3-backups
          key: username
        secretAccessKey:
          name: s3-backups
          key: password
    image:
      repository: ghcr.io/cloudnative-pg/postgresql
      tag: 18-minimal-trixie
      pullPolicy: IfNotPresent

    cluster:
      deploymentAnnotations: {}

      enabled: true
      name: db-cluster
      instances: 1
      superuser:
        credentials: db-super-credentials
      user:
        credentials: hazel-db-credentials

      storage:
        # either a size string or a full storage spec
        size: 5Gi
        # pvcTemplate:
        #   accessModes:
        #     - ReadWriteOnce
        #   resources:
        #     requests:
        #       storage: 40Gi
        #   storageClassName: manual-db
        #   volumeMode: Filesystem

      managed:
        services:
          disabledDefaultServices: ["ro", "r"]
          additional:
            - selectorType: rw
              serviceTemplate:
                metadata:
                  name: "hazel-db-svc"
                  labels:
                    "istio.io/use-waypoint": "hazel-db-waypoint"

      bootstrap:
        initdb:
          # if true, will do a normal initdb instead of restoring from backup
          # Needs db-migratejob.yaml
          enabled: true
          dbName: app
          dbOwner: user
          postInitApplicationSQL:
            - ALTER USER "user" REPLICATION;

        recovery:
          # this should be the same as the backup setup if restoring from the same backup object
          destinationPath: db-backups-recovery
          host: backups.hazel.localhost
          port: 80
          useSSL: false
          barmanObjectName: s3-store-db-other
          s3Credentials:
            accessKeyId:
              name: s3-backups
              key: username
            secretAccessKey:
              name: s3-backups
              key: password

      walArchive:
        enabled: false
        barmanObjectName: s3-store-db

      enableSuperuserAccess: true
      extraRoles: {}
      #   - name: user
      #     ensure: present
      #     comment: "normal user for hazel application"
      #     login: true
      #     superuser: true
      #     createdb: true
      #     createrole: true
      #     replication: true
      #     bypassrls: true
      #     passwordSecret:
      #       name: hazel-db-credentials

  # db:
  #   enabled: true
  #   backups:
  #     enabled: true
  #     schedule: "0 30 2 * * *"  # At 02:30:00 (UTC) every day
  #     retention: 7d          # keep 7 backups
  #     barmanObjectName: s3-store-db
  #     destinationPath: "hazel-db-backups"
  #     host: backups.hazel.localhost
  #     port: 80
  #     useSSL: false
  #     walCompression: bzip2  # bzip2;gzip;lz4;snappy;xz;zstd
  #     dataCompression: bzip2  # bzip2;gzip;snappy
  #     s3Credentials:
  #       accessKeyId:
  #         name: s3-backups
  #         key: username
  #       secretAccessKey:
  #         name: s3-backups
  #         key: password

  #   cluster:
  #     enabled: true
  #     name: db-cluster
  #     instances: 1
  #     image:
  #       repository: "ghcr.io/cloudnative-pg/postgresql"
  #       tag: "18-minimal-trixie"
  #       pullPolicy: IfNotPresent
  #     superuser:
  #       credentials: db-super-credentials
  #     user:
  #       credentials: hazel-db-credentials
  #     storage:
  #       size: 5Gi

  #     managed:
  #       services:
  #         disabledDefaultServices: ["ro", "r"]

  #     # To bootstrap a new database (needs init afterwards)
  #     bootstrap:
  #       enabled: true
  #       dbName: app
  #       dbOwner: user
  #       postInitApplicationSQL:
  #         - ALTER USER user REPLICATION;

  #       recovery:
  #         # To restore from a backup
  #         # backupSource: true
  #         barmanObjectName: s3-store-db

  #     walArchive:
  #       enabled: true
  #       barmanObjectName: s3-store-db

  #     extraRoles: []
  #       # example:
  #       # - name: notes
  #       #   ensure: present
  #       #   comment: "hazel Application User"
  #       #   login: true
  #       #   createdb: true
  #       #   createrole: false
  #       #   replication: false
  #       #   bypassrls: false
  #       #   passwordSecret:
  #       #     name: mya-db-credentials

minio:
  enabled: false
  extendedOperator:
    # Set this to create a user for hazel to use for storage
    # The secret with this name must exist and contain keys `secretKey`
    # You can use the provided `kube/kube/k3d-deploy/secrets/hazel-infra/s3-storage.json` to create such a secret
    user:
      name: s3-storage
      secretName: s3-storage
      secretKeyName: password

    buckets:
      - name: hazel
        versioning: true
      - name: hazeluploads
        versioning: true
      - name: hazelgrades
        versioning: true
      - name: hazelprofiles
        versioning: true
      - name: public
        versioning: true
        public: true
    extraBuckets: []
      # example:
      # - name: extra-bucket
      #   versioning: false

  # see https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant.yaml
  tenant:
    name: minio-storage
    exposeServices:
      minio: false
      console: false

    # DO NOT SET BUCKETS HERE! They are NOT managed by this operator - see extendedOperator above!
    # buckets: []

    configSecret:
      name: minio-env
      existingSecret: true

    certificate:
      requestAutoCert: false

    # pools:
    #   - servers: 1
    #     name: pool-0
    #     volumesPerServer: 1
    #     size: 5Gi

  ingress:
    api:
      enabled: false
      ingressClassName: "traefik"
      labels: { }
      annotations: { }
      tls: [ ]
      host: files.hazel.localhost
      path: /
      pathType: Prefix
    console:
      enabled: false
      ingressClassName: "traefik"
      labels: { }
      annotations: { }
      tls: [ ]
      host: minio-console.hazel.localhost
      path: /
      pathType: Prefix

redis:
  enabled: true
  # FIXME: externalConfig is not actually used but by being present, it avoids a bug in chart versions 0.16.7-9
  externalConfig:
    enabled: true
  redisStandalone:
    name: kv-rw  # apparently MUST be set or it will default to the release name
    tag: "v7.4.8"
    # tag: "v8.4.2"
