apiVersion: v2
name: hazel-infra
description: A Helm chart for hazelchat platform infrastructure
type: application
version: 0.1.0
appVersion: "v1"
keywords:
  - hazel
  - k3d
  - kubernetes
  - helm
home: https://github.com/HazelChat/hazel
sources:
  - https://github.com/HazelChat/hazel
maintainers:
  - name: Anton MELSER
    url: https://github.com/AntonOfTheWoods

dependencies:
  # - name: tenant
  #   version: "7.x.x"
  #   repository: "https://operator.min.io/"
  #   alias: minio
  #   condition: minio.enabled

  - name: redis
    version: "0.16.x"
    repository: "https://ot-container-kit.github.io/helm-charts/"
    condition: redis.enabled
