
global:
  instanceId: "hazel-instance"
  imagePullSecrets: []

project:
  local:
    enableNodePorts: false

# Common labels and annotations
commonLabels:
  app.kubernetes.io/part-of: hazel
  # app.kubernetes.io/managed-by: Helm
  # Additional common labels can be added here

commonAnnotations: {}
  # App version annotation will be automatically added
  # Additional annotations can be added here

hazel:
  # Dev settings
  isDev: false
  local:
    # if set and `isDev: true`, will mount a volume from this path (useful for local development)
    # WARNING: this path will be inside the k3d container if using k3d, not your host machine,
    # so if you want to use your host machine path, you need to mount it in k3d first at cluster creation time!
    # This will be done automatically if using the kube scripts
    src: true


  web:
    localRoutes: []
  botgateway:
    localRoutes: []
  docs:
    localRoutes: []
  cluster:
    localRoutes: []
  backend:
    localRoutes: []
  electricProxy:
    localRoutes: []
  landing:
    localRoutes: []
  actors:
    localRoutes: []
  # SMTP settings
  smtp:
    host: smtp.hazel.localhost
    port: 2525
    useTLS: "false"
    useSSL: "false"
    credentials:
      username:
        # set secretName to "" to disable SMTP auth
        secretName: smtp-credentials
        secretKey: username
      password:
        # set secretName to "" to disable SMTP auth
        secretName: smtp-credentials
        secretKey: password

  # Backups and Init
  # Init job to setup the platform - MUST be launched manually, see `README` for more info!
  init:
    enabled: true
    workflow:
      timeout: 3600  # 1 hour in seconds

  backups:
    # image:
    #   repository: minio/mc
    #   tag: RELEASE.2025-08-13T08-35-41Z
    #   pullPolicy: IfNotPresent

    media:
      enabled: false
      strategy:
        type: Recreate
      destination:
        bucketName: "hazel-storage"
        host: backups.hazel.localhost
        port: 80
        useSSL: false
        accessKey:
          secretName: s3-backups
          secretKey: username
        secretKey:
          secretName: s3-backups
          secretKey: password

  # Ingress, Certs
  traefik:
    enabled: true
    publicStoragePaths:
      - /public/

  # dbs, search and data stores
  cache:
    backend:
      host: redis
      port: 6379
      db: 1
      credentials: "kv-db-credentials"
  s3:
    storageBucket: "local/hazel"

    accessKey:
      secretName: s3-storage
      secretKey: username
    secretKey:
      secretName: s3-storage
      secretKey: password

    queryStringAuth: true
    signatureVersion: "s3v4"
    requestChecksumCalculation: "when_required"
    host: files.hazel.localhost
    port: 443
    useSSL: true
    s3CustomDomain: ""
    s3ProfileImageCustomDomain: ""
    defaultACL: ""
    addressingStyle: "auto"
    region: ""
  db:
    host: db-cluster-rw
    port: 5432
    name: hazel
    credentials: "hazel-db-credentials"
    options: {}
