{{- if .Values.init.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hazel-init-workflow-template
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
  labels:
    {{- include "hazel.componentLabels" (dict "component" "hazel" "root" .) | nindent 4 }}

spec:
  entrypoint: main

  {{- include "hazel.imagePullSecrets" . | nindent 2 }}

  activeDeadlineSeconds: {{ .Values.hazel.init.workflow.timeout | default 3600 }}
  serviceAccountName: argo-workflow
  templates:
  - name: main
    dag:
      tasks:
      - name: hazel-init
        template: hazel-init
      - name: hazel-migrate
        template: hazel-migrate
        dependencies: [hazel-init]

  - name: hazel-init
    container:
      image: {{ include "hazel.image" (dict "component" "hazel" "root" .) }}
      imagePullPolicy: {{ include "hazel.imagePullPolicy" (dict "component" "hazel" "root" .) }}

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          echo "FIXME: init"
      env:
        - name: INIT_THING
          value: hazel
        {{- include "hazel.common.env" . | nindent 8 }}

      volumeMounts:
        {{- include "hazel.common.volumeMounts" . | nindent 8 }}
        {{- include "hazel.dev.volumeMounts" . | nindent 8 }}
    volumes:
      {{- include "hazel.common.volumes" . | nindent 6 }}
      {{- include "hazel.dev.volumes" . | nindent 6 }}

  - name: hazel-migrate
    {{- if .Values.hazel.isDev }}
    initContainers:
    {{- include "hazel.dev.caInitContainerForComponent" (dict "component" "hazel" "root" .) | nindent 4 }}
    {{- end }}
    container:
      image: {{ include "hazel.image" (dict "component" "hazel" "root" .) }}
      imagePullPolicy: {{ include "hazel.imagePullPolicy" (dict "component" "hazel" "root" .) }}

      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          set -e
          echo "FIXME: init"
          echo "hazel migration and setup completed successfully"
      env:
        - name: INIT_THING
          value: hazel
        {{- include "hazel.common.env" . | nindent 8 }}

      volumeMounts:
        {{- include "hazel.common.volumeMounts" . | nindent 8 }}
        {{- include "hazel.dev.volumeMounts" . | nindent 8 }}
        {{- include "hazel.dev.caVolumeMounts" . | nindent 8 }}
        - mountPath: /hazel/media
          name: media-storage
    volumes:
      {{- include "hazel.common.volumes" . | nindent 6 }}
      {{- include "hazel.dev.volumes" . | nindent 6 }}
      {{- include "hazel.dev.caVolumes" . | nindent 6 }}
      - name: media-storage
        emptyDir: {}

{{- end }}
