apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: s3-key
  # namespace: garage-operator-system
  # namespace: datest
spec:
  clusterRef:
    name: garage
  name: s3-key

  # Import from existing secret
  importKey:
    accessKeyIdKey: username
    secretAccessKeyKey: password
    secretRef:
      name: s3-storage
      # namespace: datest

  bucketPermissions:
    - globalAlias: hazel-bucket
      read: true
