{{- if and false .Values.hazel.enabled .Values.hazel.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
  labels:
    {{- include "hazel.componentLabels" (dict "component" "backend" "root" .) | nindent 4 }}
spec:
  progressDeadlineSeconds: {{ .Values.hazel.backend.progressDeadlineSeconds | default 600 }}
  replicas: {{ if hasKey .Values.hazel.backend "replicas" }}{{ .Values.hazel.backend.replicas }}{{ else }}1{{ end }}
  revisionHistoryLimit: {{ .Values.hazel.backend.revisionHistoryLimit | default 10 }}

  selector:
    matchLabels:
      {{- include "hazel.componentSelectorLabels" (dict "component" "backend" "root" .) | nindent 6 }}

  {{- if .Values.hazel.backend.updateStrategy }}
  strategy: {{- toYaml .Values.hazel.backend.updateStrategy | nindent 4 }}
  {{- end }}

  template:
    metadata:
      annotations:
        {{- include "hazel.annotations" . | nindent 8 }}
      labels:
        {{- include "hazel.componentLabels" (dict "component" "backend" "root" .) | nindent 8 }}
    spec:
      dnsPolicy: {{ .Values.hazel.backend.dnsPolicy | default "ClusterFirst" }}
      restartPolicy: {{ .Values.hazel.backend.restartPolicy | default "Always" }}
      schedulerName: {{ .Values.hazel.backend.schedulerName | default "default-scheduler" }}
      # securityContext: { toYaml .Values.hazel.backend.securityContext | default (dict) }
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: {{ .Values.hazel.backend.terminationGracePeriodSeconds | default 30 }}

      {{- include "hazel.imagePullSecrets" . | nindent 6 }}

      containers:
      - name: backend
        image: {{ include "hazel.image" (dict "component" "backend" "root" .) }}
        imagePullPolicy: {{ include "hazel.imagePullPolicy" (dict "component" "backend" "root" .) }}

        {{- if .Values.hazel.backend.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.diagnosticMode.command "context" $) | nindent 10 }}
        {{- else if .Values.hazel.backend.command }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.command "context" $) | nindent 10 }}
        {{- else }}
        command: ["gunicorn"]
        {{- end }}

        {{- if .Values.hazel.backend.diagnosticMode.enabled }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else if .Values.hazel.backend.args }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.args "context" $) | nindent 11 }}
        {{- else }}
        args:
          - ""
        {{- end }}

        ports:
        - containerPort: {{ .Values.hazel.backend.application.port }}
          protocol: TCP

        {{- if .Values.hazel.backend.resources }}
        resources: {{- toYaml .Values.hazel.backend.resources | nindent 12 }}
        {{- end }}

        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: {{ .Values.hazel.backend.terminationMessagePath | default "/dev/termination-log" }}
        terminationMessagePolicy: {{ .Values.hazel.backend.terminationMessagePolicy | default "File" }}

        env:
        {{- include "hazel.backend.env" . | nindent 8 }}
        {{- include "hazel.database.envvars" . | nindent 8 }}
        - name: PORT
          value: {{ .Values.hazel.backend.application.port | quote }}
        - name: IS_DEV
          value: {{ .Values.hazel.isDev | quote }}
        - name: FRONTEND_URL # FIXME:
          value: {{ .Values.hazel.frontend.url | quote }}
        # FRONTEND_URL=http://localhost:3000
        - name: API_BASE_URL
          value: {{ .Values.hazel.backend.apiBaseUrl | quote }}
        # API_BASE_URL=http://localhost:3003
        - name: CLUSTER_URL
          value: {{ .Values.hazel.clusterUrl | quote }}
        # CLUSTER_URL=http://localhost:3020
        {{- include "hazel.kv.envvars" . | nindent 8 }}
        # REDIS_URL=redis://localhost:6380
        - name: ELECTRIC_URL
          value: {{ template "project.electric.fullname" . }}
        # ELECTRIC_URL=http://localhost:3333
        - name: WORKOS_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hazel.workos.apiKey.secretName | default "workos-secretkey" | quote }}
              key: {{ .Values.hazel.workos.apiKey.secretKey | default "apiKey" | quote }}
        - name: WORKOS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hazel.workos.clientId.secretName | default "workos-secretkey" | quote }}
              key: {{ .Values.hazel.workos.clientId.secretKey | default "clientId" | quote }}
        - name: WORKOS_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hazel.workos.webhookSecret.secretName | default "workos-secretkey" | quote }}
              key: {{ .Values.hazel.workos.webhookSecret.secretKey | default "webhook" | quote }}
        - name: WORKOS_COOKIE_DOMAIN
          value: {{ .Values.hazel.workos.cookieDomain | quote }}
        - name: WORKOS_REDIRECT_URI
          value: {{ .Values.hazel.workos.redirectUri | quote }}
        - name: INTEGRATION_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hazel.integration.encryptionKey.secretName | default "integration-encryption-key" | quote }}
              key: {{ .Values.hazel.integration.encryptionKey.secretKey | default "key" | quote }}
        - name: INTEGRATION_ENCRYPTION_KEY_VERSION
          value: {{ .Values.hazel.integration.encryptionKey.version | default 1 | quote }}

        - name: S3_ENDPOINT
          value: {{ .Values.hazel.cache.s3.host | quote }}

        # S3_BUCKET=hazel
        # S3_ENDPOINT=http://localhost:9000
        # S3_ACCESS_KEY_ID=minioadmin
        # S3_SECRET_ACCESS_KEY=minioadmin
        # LINEAR_CLIENT_ID=your_client_id
        # LINEAR_CLIENT_SECRET=your_client_secret
        # LINEAR_REDIRECT_URI=http://localhost:3003/integrations/linear/callback
        # GITHUB_APP_ID=
        # GITHUB_APP_SLUG=
        # GITHUB_APP_PRIVATE_KEY=
        # GITHUB_WEBHOOK_SECRET=
        # KLIPY_API_KEY=none
        {{- if .Values.hazel.backend.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.extraEnvVars "context" $) | nindent 8 }}
        {{- end }}

        volumeMounts:
        {{- include "hazel.dev.volumeMounts" . | nindent 8 }}

        {{- if .Values.hazel.backend.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.extraVolumeMounts "context" $) | nindent 8 }}
        {{- end }}

        {{- if .Values.hazel.backend.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.hazel.backend.sidecars "context" $) | nindent 8 }}
        {{- end }}

      volumes:
      # - name: settings
      #   configMap:
      #     name: backend-settings
      #     defaultMode: 420
      {{- include "hazel.dev.volumes" . | nindent 6 }}

      {{- if .Values.hazel.backend.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.hazel.backend.extraVolumes "context" $) | nindent 6 }}
      {{- end }}

{{- end -}}
