apiVersion: v2
name: hazel
description: A Helm chart for hacking on and deploying the hazel.sh platform
type: application
version: 0.1.0
appVersion: "v1"
keywords:
  - hazel
  - k3d
  - kubernetes
  - helm
home: https://github.com/HazelChat/hazel
sources:
  - https://github.com/HazelChat/hazel
maintainers:
  - name: Anton MELSER
    url: https://github.com/AntonOfTheWoods
