{{- if and .Values.hazel.enabled .Values.hazel.web.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazel-settings
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
  labels:
    {{- include "hazel.componentLabels" (dict "component" "hazel" "root" .) | nindent 4 }}
data:
  afile.conf: ""

{{- end -}}
