{{- if and false .Values.hazel.enabled .Values.hazel.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
  labels:
    {{- include "hazel.componentLabels" (dict "component" "web" "root" .) | nindent 4 }}
spec:
  progressDeadlineSeconds: {{ .Values.hazel.web.progressDeadlineSeconds | default 600 }}
  replicas: {{ if hasKey .Values.hazel.web "replicas" }}{{ .Values.hazel.web.replicas }}{{ else }}1{{ end }}
  revisionHistoryLimit: {{ .Values.hazel.web.revisionHistoryLimit | default 10 }}

  selector:
    matchLabels:
      {{- include "hazel.componentSelectorLabels" (dict "component" "web" "root" .) | nindent 6 }}

  {{- if .Values.hazel.web.updateStrategy }}
  strategy: {{- toYaml .Values.hazel.web.updateStrategy | nindent 4 }}
  {{- end }}

  template:
    metadata:
      annotations:
        {{- include "hazel.annotations" . | nindent 8 }}
      labels:
        {{- include "hazel.componentLabels" (dict "component" "web" "root" .) | nindent 8 }}
    spec:
      dnsPolicy: {{ .Values.hazel.web.dnsPolicy | default "ClusterFirst" }}
      restartPolicy: {{ .Values.hazel.web.restartPolicy | default "Always" }}
      schedulerName: {{ .Values.hazel.web.schedulerName | default "default-scheduler" }}
      # securityContext: { toYaml .Values.hazel.web.securityContext | default (dict) }
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: {{ .Values.hazel.web.terminationGracePeriodSeconds | default 30 }}

      {{- include "hazel.imagePullSecrets" . | nindent 6 }}

      {{- if .Values.hazel.isDev }}
      initContainers:
      {{- include "hazel.dev.caInitContainerForComponent" (dict "component" "web" "root" .) | nindent 6 }}
      {{- end }}

      containers:
      - name: {{ .Values.hazel.web.application.name | default "web" }}
        image: {{ include "hazel.image" (dict "component" "web" "root" .) }}
        imagePullPolicy: {{ include "hazel.imagePullPolicy" (dict "component" "web" "root" .) }}

        {{- if .Values.hazel.web.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.diagnosticMode.command "context" $) | nindent 10 }}
        {{- else if .Values.hazel.web.command }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.command "context" $) | nindent 10 }}
        {{- else if .Values.hazel.isDev }}
        command:
        - /bin/sh
        - -c
        args:
        - |
          {{- include "hazel.dev.startupScript" . | nindent 10 }}
          exec uwsgi --ini /hazel/uwsgi.ini
        {{- end }}
        {{- if .Values.hazel.web.diagnosticMode.enabled }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else if and .Values.hazel.web.args (not .Values.hazel.isDev) }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.args "context" $) | nindent 11 }}
        {{- end }}

        ports:
        - containerPort: {{ .Values.hazel.web.application.port | default 8000 }}
          protocol: TCP

        # resources:
        #   requests:
        #     memory: 2Gi
        {{- if .Values.hazel.web.resources }}
        resources: {{- toYaml .Values.hazel.web.resources | nindent 12 }}
        {{- end }}

        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: {{ .Values.hazel.web.terminationMessagePath | default "/dev/termination-log" }}
        terminationMessagePolicy: {{ .Values.hazel.web.terminationMessagePolicy | default "File" }}

        env:
        - name: LISTEN_PORT
          value: {{ .Values.hazel.web.application.port | default 8000 | quote }}

        - name: SITE_ID
          value: {{ .Values.hazel.web.siteId | quote }}

        {{- include "hazel.common.env" . | nindent 8 }}

        {{- if .Values.hazel.web.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.extraEnvVars "context" $) | nindent 8 }}
        {{- end }}

        volumeMounts:
        {{- include "hazel.common.volumeMounts" . | nindent 8 }}
        {{- include "hazel.dev.volumeMounts" . | nindent 8 }}
        {{- include "hazel.dev.caVolumeMounts" . | nindent 8 }}
        {{- if .Values.hazel.web.extraVolumeMounts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.extraVolumeMounts "context" $) | nindent 8 }}
        {{- end }}

        {{- if .Values.hazel.web.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.hazel.web.sidecars "context" $) | nindent 8 }}
        {{- end }}

      volumes:
      {{- include "hazel.common.volumes" . | nindent 6 }}
      {{- include "hazel.dev.volumes" . | nindent 6 }}
      {{- include "hazel.dev.caVolumes" . | nindent 6 }}
      {{- if .Values.hazel.web.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.hazel.web.extraVolumes "context" $) | nindent 6 }}
      {{- end }}

{{- end -}}
