{{- if and .Values.hazel.traefik.enabled .Values.hazel.web.enabled -}}
{{- $host := .Values.hazel.web.host }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: favicon-rewrite
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: ^/favicon\.ico$
    replacement: /theming/asset/images/favicon.ico
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: profile-upload-limit
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.hazel.web.ingress.profileUpload.maxRequestBodyBytes | default 1048576 }}  # 1MB
    memRequestBodyBytes: {{ .Values.hazel.web.ingress.profileUpload.memRequestBodyBytes | default 1048576 }}
    maxResponseBodyBytes: {{ .Values.hazel.web.ingress.profileUpload.maxResponseBodyBytes | default 0 }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-body-limit
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.hazel.web.ingress.default.maxRequestBodyBytes | default 4194304 }}  # 4MB
    memRequestBodyBytes: {{ .Values.hazel.web.ingress.default.memRequestBodyBytes | default 4194304 }}
    maxResponseBodyBytes: {{ .Values.hazel.web.ingress.default.maxResponseBodyBytes | default 0 }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingressroute
  annotations:
    {{- include "hazel.annotations" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
{{- range .Values.hazel.web.localRoutes }}
    - match: Host(`{{ .host | default $host }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      middlewares:
        - name: add-headers
        - name: compress-gzip
        - name: cors-allowed-origins
{{- if .suppressPath }}
        - name: stripprefix-web-{{ .name }}
{{- end }}
      services:
        - name: external-web-{{ .name }}
          port: {{ .port }}
{{- end }}
    - match: Host(`{{ $host }}`) && PathPrefix(`/api/profile_images`)
      kind: Rule
      middlewares:
      - name: favicon-rewrite
      - name: profile-upload-limit
      services:
      - name: {{ .Values.hazel.web.service.name | default "web" }}
        port: {{ .Values.hazel.web.service.port | default 8000 }}
    - match: Host(`{{ $host }}`)
      kind: Rule
      middlewares:
      - name: favicon-rewrite
      - name: default-body-limit
      - name: add-headers
      - name: compress-gzip
      - name: cors-allowed-origins
      services:
      - name: {{ .Values.hazel.web.service.name | default "web" }}
        port: {{ .Values.hazel.web.service.port | default 8000 }}
  tls:
    {{- include "hazel.ingressroute.tlsname" (dict "component" "web" "root" .) | nindent 4 }}
---
{{- include "hazel.ingressroute.tlscertificate" (dict "component" "web" "root" .) }}

{{- end -}}
