{{- $root := . -}}
{{- $clusters := $root.Values.dbClusters -}}
{{- if $clusters }}
{{- range $name, $cfg := $clusters }}
{{- if $cfg.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $cfg.cluster.name | default (printf "%s-%s" (include "common.names.name" $root) $name) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $root.Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: db-cluster
    hazel.cluster: {{ $name }}
  {{- if or $cfg.deploymentAnnotations $root.Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list $cfg.deploymentAnnotations $root.Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
  {{- end }}

spec:
  instances: {{ $cfg.cluster.instances | default 1 }}
  imageName: {{ $cfg.image.repository | default "ghcr.io/cloudnative-pg" }}:{{ $cfg.image.tag | default "18-standard-trixie" }}
  imagePullPolicy: {{ $cfg.image.pullPolicy | default "IfNotPresent" }}
  {{/*
  {{- include "hazel.imagePullSecrets" $cfg.image | nindent 2 }}
  */}}

  superuserSecret:
    name: {{ $cfg.cluster.superuser.credentials | default (printf "%s-%s-super-credentials" (include "common.names.name" $root) $name) }}
  {{- if $cfg.cluster.postgresUID }}
  postgresUID: {{ $cfg.cluster.postgresUID }}
  {{- end }}
  {{- if $cfg.cluster.postgresGID }}
  postgresGID: {{ $cfg.cluster.postgresGID }}
  {{- end }}
  enableSuperuserAccess: {{ $cfg.cluster.enableSuperuserAccess | default false }}

  {{- with $cfg.cluster.storage }}
  storage:
    {{- toYaml . | nindent 6 }}
  {{- end }}

  bootstrap:
  {{- if and $cfg.cluster.bootstrap.initdb $cfg.cluster.bootstrap.initdb.enabled }}
    initdb:
      database: {{ $cfg.cluster.bootstrap.initdb.dbName | default "transcrobes" }}
      owner: {{ $cfg.cluster.bootstrap.initdb.dbOwner | default "transcrobes" }}
      secret:
        name: {{ $cfg.cluster.user.credentials | default (printf "%s-%s-db-credentials" (include "common.names.name" $root) $name) }}
      {{- if $cfg.cluster.bootstrap.initdb.postInitApplicationSQL }}
      postInitApplicationSQL:
        {{- toYaml $cfg.cluster.bootstrap.initdb.postInitApplicationSQL | nindent 8 }}
      {{- end }}

  {{- else }}
    recovery:
      source: {{ $cfg.cluster.bootstrap.recovery.source | default (printf "%s-%s-bootstrap-source" (include "common.names.name" $root) $name) }}
  externalClusters:
  - name: {{ $cfg.cluster.bootstrap.recovery.externalClusterName | default (printf "%s-%s-bootstrap-source" (include "common.names.name" $root) $name) }}
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: {{ $cfg.cluster.bootstrap.recovery.barmanObjectName | default "db-backups-recovery" }}
  {{- end }}

  {{- if and $cfg.cluster.walArchive $cfg.cluster.walArchive.enabled $cfg.cluster.walArchive.barmanObjectName }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: {{ $cfg.cluster.walArchive.enabled | default false }}
    parameters:
      barmanObjectName: {{ $cfg.cluster.walArchive.barmanObjectName | default "s3-store-db" }}
  {{- end }}

  {{- if $cfg.cluster.postgresql }}
  postgresql:
    {{- with $cfg.cluster.postgresql.shared_preload_libraries }}
    shared_preload_libraries:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $cfg.cluster.postgresql.pg_hba }}
    pg_hba:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $cfg.cluster.postgresql.pg_ident }}
    pg_ident:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $cfg.cluster.postgresql.parameters }}
    parameters:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with $cfg.cluster.postgresql.extensions }}
    extensions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if and $cfg.projectedVolumeTemplate $cfg.projectedVolumeTemplate.sources }}
  projectedVolumeTemplate:
    {{- with $cfg.projectedVolumeTemplate.sources }}
    sources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if or (and $cfg.cluster.managed $cfg.cluster.managed.services) $cfg.cluster.extraRoles }}
  managed:
    {{- if dig "managed" "services" "false" $cfg.cluster }}
    {{- with $cfg.cluster.managed.services }}
    services:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}

    {{- if $cfg.cluster.extraRoles }}
    roles:
      {{- toYaml $cfg.cluster.extraRoles | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
