{{- if .Values.electric.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "electric.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: electric
    app.kubernetes.io/part-of: hazel
  {{- if or .Values.electric.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.electric.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.electric.replicaCount }}
  {{- if .Values.electric.strategy }}
  strategy:
{{ toYaml .Values.electric.strategy | indent 4 }}
  {{- end }}

  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.electric.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: electric
      app.kubernetes.io/part-of: hazel
  template:
    metadata:
      {{- if .Values.electric.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.electric.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: electric
        app.kubernetes.io/part-of: hazel

    spec:
      initContainers:
        {{- if .Values.defaultInitContainers.waitForDB.enabled }}
        {{- include "hazel.initContainers.waitForDB" . | nindent 8 }}
        {{- end }}

      containers:
      - name: electric
        image: {{ include "electric.image" . }}
        imagePullPolicy: {{ .Values.electric.image.pullPolicy }}

        env:
        {{- include "hazel.configure.database" . | indent 8 }}

        - name: ELECTRIC_PORT
          value: {{ .Values.electric.containerPorts.http | quote }}
        - name: ELECTRIC_STORAGE_DIR
          value: {{ .Values.electric.persistence.mountPath }}

        - name: ELECTRIC_TCP_SEND_TIMEOUT
          value: {{ .Values.electric.tcpSendTimeout | default "600s" | quote }}

        {{- if .Values.electric.insecureApi }}
        - name: ELECTRIC_INSECURE
          value: "true"
        {{- else }}
        - name: ELECTRIC_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.electric.apiTokenSecretName }}
              key: {{ .Values.electric.apiTokenSecretKey }}
        {{- end }}

        {{- if .Values.electric.extraEnvVars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.electric.extraEnvVars "context" $) | nindent 8 }}
        {{- end }}

        volumeMounts:
        - name: {{ .Values.electric.persistence.volumeName }}
          mountPath: {{ .Values.electric.persistence.mountPath }}
          {{- if .Values.electric.persistence.subPath }}
          subPath: {{ .Values.electric.persistence.subPath }}
          {{- end }}

      volumes:
      - name: {{ .Values.electric.persistence.volumeName }}
  {{- if and .Values.electric.persistence.enabled .Values.electric.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ tpl .Values.electric.persistence.existingClaim $ }}
  {{- else if not .Values.electric.persistence.enabled }}
        emptyDir: {}
  {{- else }}
        persistentVolumeClaim:
          claimName: {{ .Values.electric.persistence.volumeName }}
  {{- end }}
{{- end }}
