{{- if and .Values.electric.persistence.enabled (not .Values.electric.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.electric.persistence.volumeName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: electric
    app.kubernetes.io/part-of: hazel
  {{- if or .Values.electric.persistence.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.electric.persistence.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}

spec:
  accessModes:
  {{- range .Values.electric.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.electric.persistence.size | quote }}
  {{- if .Values.electric.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.electric.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.electric.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.electric.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.electric.persistence "global" .Values.global) | nindent 2 }}
{{- end -}}
