{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $root := . -}}
{{- $appKeys := include "hazel.app.keysFor" (dict "root" $root "kind" "hpa") | fromYamlArray -}}
{{ range $appKey := $appKeys }}
{{ $app := include "hazel.app.config" (dict "root" $root "appKey" $appKey) | fromYaml -}}
{{- $autoscaling := default (dict) $app.autoscaling -}}
{{- $hpa := default (dict) $autoscaling.hpa -}}
{{ if and (eq (include "hazel.app.enabled" (dict "root" $root "appKey" $appKey) | trim) "true") (default false $hpa.enabled) }}
{{- $fullname := include "hazel.app.fullname" (dict "root" $root "appKey" $appKey) -}}
{{- $component := include "hazel.app.component" (dict "appKey" $appKey) -}}
---
apiVersion: {{ include "common.capabilities.hpa.apiVersion" $root }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullname }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $root.Values.commonLabels "context" $root ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: hazel
  {{- if $root.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $root.Values.commonAnnotations "context" $root ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" $root }}
    kind: Deployment
    name: {{ $fullname }}
  minReplicas: {{ $hpa.minReplicas }}
  maxReplicas: {{ $hpa.maxReplicas }}
  metrics:
    {{- if $hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetMemory }}
    {{- end }}
    {{- if $hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $hpa.targetCPU }}
    {{- end }}
{{- end }}
{{- end }}
