{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $root := . -}}
{{- $appKeys := include "hazel.app.keysFor" (dict "root" $root "kind" "pdb") | fromYamlArray -}}
{{ range $appKey := $appKeys }}
{{ $app := include "hazel.app.config" (dict "root" $root "appKey" $appKey) | fromYaml -}}
{{- $pdb := default (dict) $app.pdb -}}
{{ if and (eq (include "hazel.app.enabled" (dict "root" $root "appKey" $appKey) | trim) "true") (default false $pdb.create) }}
{{- $fullname := include "hazel.app.fullname" (dict "root" $root "appKey" $appKey) -}}
{{- $component := include "hazel.app.component" (dict "appKey" $appKey) -}}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" $root }}
kind: PodDisruptionBudget
metadata:
  name: {{ $fullname }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $root.Values.commonLabels "context" $root ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: hazel
  {{- if $root.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $root.Values.commonAnnotations "context" $root ) | nindent 4 }}
  {{- end }}
spec:
  {{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
  {{- end  }}
  {{- if or $pdb.maxUnavailable ( not $pdb.minAvailable ) }}
  maxUnavailable: {{ $pdb.maxUnavailable | default 1 }}
  {{- end  }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list $app.podLabels $root.Values.commonLabels) "context" $root) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $root ) | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
      app.kubernetes.io/part-of: hazel
{{- end }}
{{- end }}
