{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $root := . -}}
{{- $appKeys := include "hazel.app.keysFor" (dict "root" $root "kind" "vpa") | fromYamlArray -}}
{{ range $appKey := $appKeys }}
{{ $app := include "hazel.app.config" (dict "root" $root "appKey" $appKey) | fromYaml -}}
{{- $autoscaling := default (dict) $app.autoscaling -}}
{{- $vpa := default (dict) $autoscaling.vpa -}}
{{ if and (eq (include "hazel.app.enabled" (dict "root" $root "appKey" $appKey) | trim) "true") (include "common.capabilities.apiVersions.has" ( dict "version" "autoscaling.k8s.io/v1/VerticalPodAutoscaler" "context" $root )) (default false $vpa.enabled) }}
{{- $fullname := include "hazel.app.fullname" (dict "root" $root "appKey" $appKey) -}}
{{- $component := include "hazel.app.component" (dict "appKey" $appKey) -}}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $fullname }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $root.Values.commonLabels "context" $root ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/part-of: hazel
  {{- if or $vpa.annotations $root.Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $vpa.annotations $root.Values.commonAnnotations ) "context" $root ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $root) | nindent 4 }}
  {{- end }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ $component }}
      {{- with $vpa.controlledResources }}
      controlledResources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $vpa.maxAllowed }}
      maxAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $vpa.minAllowed }}
      minAllowed:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  targetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" $root }}
    kind: "Deployment"
    name: {{ $fullname }}
  {{- if $vpa.updatePolicy }}
  updatePolicy:
    {{- with $vpa.updatePolicy.updateMode }}
    updateMode: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
